import type { ClimbWeather } from "../types/weather";

type WeatherSummaryProps = {
  weather: ClimbWeather;
};

export function WeatherSummary({ weather }: WeatherSummaryProps) {
  const summary = weather.phraseSummary;

  return (
    <section className="panel weather-summary">
      <div className="section-heading">
        <p className="eyebrow">Weather summary</p>
        <h2>Xweather Phrases context</h2>
      </div>
      {summary.text ? (
        <p>{summary.text}</p>
      ) : (
        <p>
          Phrases API summary unavailable for this request. The climb score
          still uses observations, forecast, alerts, recent precipitation, and
          threat data when available.
        </p>
      )}
      <span>
        {summary.source === "phrases"
          ? "Generated by Xweather Phrases API. The climb score remains deterministic."
          : summary.source === "mock"
            ? "Mock phrase summary for local development."
            : "Optional Phrases API data was not returned."}
      </span>
    </section>
  );
}
